### ISSUE TITLE
Add a vendor file, pls

### ISSUE THREAD

**Issue by henson** [muesli/beehive#87] opened 2017-02-14 15:06 UTC
Your work is great. 
Can you add a vendor file to managed the dependencies with the govendor or godep tool. It will be easy for others to build your project.
Thank u!

**Comment by muesli** [comment] 2017-02-14 15:22
I must admit I'm not really convinced that the current vendoring strategy is a good idea. We could include it as a git-submodule, but I'm really not excited by polluting the git-tree in any other way. Then again, maybe I just haven't suffered enough from upstream API breakage.

**Comment by muesli** [comment] 2017-02-14 17:29
I've created https://github.com/muesli/beehive-vendor

There's currently a ```vendoring``` branch for Beehive, which contains this repo as a git submodule. Let me know if this works as intended, please.

**Comment by henson** [comment] 2017-02-15 02:01
Thank u, first.
Some of the dependencies could not be downloaded correctly here. 
Now,  I can download the _beehive-vendor_ to build the same dependencies as yours easily.
Thank u again.

**Comment by muesli** [comment] 2017-05-14 03:20
Fixed in master.

**Closed by muesli** 2017-05-14 03:20 UTC
Labels: improvement
